11 get reviews queries, ready for review
LKFULLER1/portfolioProject pull request #10
Opened 2022-11-17 15:13 UTC by LKFULLER1

2022-11-17 16:19 UTC, mezzDavies requested changes
Most of the work has been done but there are a couple of considerations/ammends Have a look at my comments - hopefully they will point you in the right direction. Once you've done please resubmit the PR 👍

2022-11-17 16:19 UTC, mezzDavies commented on __tests__/app.test.js
> +  });
Good stuff, although we could do with just one more test test here. We need to consider what happens if a valid category is passed but there are no results for that category

2022-11-17 16:19 UTC, mezzDavies commented on models/games.js
> +    const validCategories = [
Unlike order and sort queries we cannot/should not green list the categories, as in reality - on a production server - it will be an ever growing list of user-generated categories. We would have to add to the green list every time a new category was added which isn't possible. 

So instead we need to use the dollar syntax to prevent injection for this query. See if you can implement this. 👍

2022-11-17 16:19 UTC, mezzDavies commented on models/games.js
> +      `SELECT owner,
The query string should be built up dynamically, with conditional logic, according to the presence - or not - of the queries E.G.
`let queryString = "start of query"`
Conditional logic to build queryString up.
You can then  pass it like this `db.query(queryString)`

2022-11-18 10:35 UTC, LKFULLER1 commented on models/games.js
> +      `SELECT owner,
Ah I see - I understand this, but this is why I have the defaults and the reviews.category = reviews.category, meaning that just the one query should work just as well

2022-11-18 11:40 UTC, Rayhaan2k9 approved these changes
👏 👏

2022-11-18 11:56 UTC, merged