4 get api reviews
LKFULLER1/portfolioProject pull request #3
Opened 2022-11-14 15:09 UTC by LKFULLER1

2022-11-14 16:04 UTC, mezzDavies requested changes
Hi, Please have a look at the the properties that are required on each object that this endpoint sends back - it's not as simple as selecting everything from the reviews table unfortunately. I have left some comments that should point you in the right direction 👍

2022-11-14 16:04 UTC, mezzDavies commented on __tests__/app.test.js
> +            title: expect.any(String),
Please double check what the ticket asks for to be returned and check for it here - there are properties that need adding and some that need removing from the assertion.

2022-11-14 16:04 UTC, mezzDavies commented on __tests__/app.test.js
> +          });
We also need check that the objects in the array are sorted by date in descending order.

2022-11-14 16:04 UTC, mezzDavies commented on models/games.js
> +    return db.query('SELECT * FROM reviews;')
This returns all columns from the reviews table but the ticket asks for so this query needs work to get all the required columns.

2022-11-14 16:07 UTC, LKFULLER1 commented on models/games.js
> +    return db.query('SELECT * FROM reviews;')
I realised I hasn't read the ticket and have now implemented much more of the task, just stuck on a toBeSortedBy test - saying it is not a function

2022-11-15 09:41 UTC, mezzDavies approved these changes
Good stuff. make sure you see the note to hopefully help you get jest-sorted working.

2022-11-15 09:41 UTC, mezzDavies commented on __tests__/app.test.js
> +            title: expect.any(String),
Well done - comment_count added. Also the category property is repeated in this assertion - one of them can be removed.

2022-11-15 09:41 UTC, mezzDavies commented on package.json
>      "setupFilesAfterEnv": [
Add jest-sorted to this array and then that should fix your "not a function" problem.

2022-11-15 10:03 UTC, merged