7 ready for review
LKFULLER1/portfolioProject pull request #6
Opened 2022-11-15 15:02 UTC by LKFULLER1

2022-11-15 16:51 UTC, mezzDavies requested changes
I think you aren't quite on top of how this endpoint works regarding the ID in the URL. I've left some comments that should point you in the right direction 😄 . This needs amending for all the test/code of the endpoint thus far. 

Once that's done there a few more things to consider testing and accounting for too eg passing a valid but non-existent id eg 99999999999,  if the username doesn't exist. Please consider the error codes for these possibilities too. 👍

2022-11-15 16:51 UTC, mezzDavies commented on __tests__/app.test.js
> +      review_id: REVIEW_ID
The ticket states the only things on the request body are the author and body properties. So we don't/shouldn't need to include the review ID here - it is in the URL as a parameter (and can be accessed by your controller on req.params).

2022-11-15 16:51 UTC, mezzDavies commented on controllers/games.js
> +  insertCommentByReviewId(req.body).then((comment) => {
The id needs to be taken from req.params not the request body. You have doen this in your getCommentsByReviewId controller above. You'll just need to pass more arguments to your insertCommentByReviewId model when you have got hold of it and the request.

2022-11-15 16:51 UTC, mezzDavies commented on __tests__/app.test.js
> +      .post(`/api/reviews/${REVIEW_ID}/comments`)
We can just pass in the id in to the url - no variable needed.

2022-11-15 16:51 UTC, mezzDavies commented on __tests__/app.test.js
> +      .then(() => {
Could this be split into two separate tests?

2022-11-15 16:51 UTC, mezzDavies commented on __tests__/app.test.js
> +  test('status:404, responds with a 404 error when the review_id does not exist', () => {
This test will need amending to accommodate for the ID being on req.params

2022-11-16 09:00 UTC, MKD01 approved these changes
Looks good, im happy for this to be merged

2022-11-16 09:01 UTC, merged